templates = {
    "agreeableness_regression_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, score the user's agreeableness. The possible range of decimal scores is 1-5.\n\n",
    
    "agreeableness_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, rate their agreeableness. The options on the scale are low, medium, high.\nAgreeableness:\n\n",

    "agreeableness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, is this user agreeable according to the Big 5 personality traits? Select between yes or no\n\n",

    "textbook_agreeableness_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to be good-natured, compliant, modest, gentle, and cooperative while individuals that are not agreeable tend to be irritable, ruthless, suspicious and inflexible. Given these messages from a user, rate their agreeableness. The options on the scale are 1 (low), 2 (medium), 3 (high)\nAgreeableness:\n\n",

    "textbook_agreeableness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to be good-natured, compliant, modest, gentle, and cooperative while individuals that are not agreeable tend to be irritable, ruthless, suspicious and inflexible. Given these messages from a user, is this user agreeable according to the Big 5 personality traits? Select between yes or no\n\n",

    "wordlist_agreeableness_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to use words like excited, blessed, great, wonderful, amazing while individuals that are not agreeable tend to use words like fuck, shit, bitch, damn, hell. Given these messages from a user, rate their agreeableness. The options on the scale are low, medium, high.\nAgreeableness:\n\n",

    "wordlist_agreeableness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to use words like excited, blessed, great, wonderful, amazing while individuals that are not agreeable tend to use words like fuck, shit, bitch, damn, hell. Given these messages from a user, is this user agreeable according to the Big 5 personality traits? Select between yes or no\n\n",

    "itemdesc_agreeableness_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to believe that others have good intentions while individuals that are not agreeable tend to hold a grudge. Given these messages from a user, rate their agreeableness according to the Big 5 personality traits. The options are low, medium, high.\nAgreeableness:\n\n",

    "itemdesc_agreeableness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to believe that others have good intentions while individuals that are not agreeable tend to hold a grudge. Given these messages from a user, is this user agreeable according to the Big 5 personality traits? Select between yes or no\n\n",

    "all_items_itemdesc_agreeableness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to believe that others have good intentions and are easy to satisfy while individuals that are not agreeable tend to hold a grudge and cut others to pieces. Given these messages from a user, is this user agreeable according to the Big 5 personality traits? Select between yes or no\n\n",

    "both_alternate_items_itemdesc_agreeableness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to be easy to satisfy while individuals that are not agreeable tend to cut others to pieces. Given these messages from a user, is this user agreeable according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_positive_item_itemdesc_agreeableness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to be easy to satisfy while individuals that are not agreeable tend to hold a grudge. Given these messages from a user, is this user agreeable according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_negative_item_itemdesc_agreeableness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to believe that others have good intentions while individuals that are not agreeable tend to cut others to pieces. Given these messages from a user, is this user agreeable according to the Big 5 personality traits? Select between yes or no\n\n",

    "all_knowledge_agreeableness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are agreeable tend to be good-natured, compliant, modest, gentle, and cooperative while individuals that are not agreeable tend to be irritable, ruthless, suspicious and inflexible. Also note that individuals who are agreeable tend to use words like excited, blessed, great, wonderful, amazing while individuals that are not agreeable tend to use words like fuck, shit, bitch, damn, hell. Furthermore, note that individuals who are agreeable tend to believe that others have good intentions and are easy to satisfy while individuals that are not agreeable tend to hold a grudge and cut others to pieces. Given these messages from a user, is this user agreeable according to the Big 5 personality traits? Select between yes or no\n\n",

    "extraversion_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, rate their extraversion. The options on the scale are low, medium, high.\nExtraversion:\n\n",

    "extraversion_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, is this user extraverted according to the Big 5 personality traits? Select between yes or no\n\n",

    "textbook_extraversion_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to be sociable, talkative, assertive and active while individuals that are not extraverted tend to be retiring, reserved and cautious. Given these messages from a user, is this user extraverted according to the Big 5 personality traits? Select between yes or no\n\n",

    "wordlist_extraversion_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to use words like party, girls, baby, gettin, chillin while individuals that are not extraverted tend to use words like anime, manga, internet, japanese, drawing. Given these messages from a user, rate their extraversion. The options on the scale are low, medium, high.\nExtraversion:\n\n",

    "wordlist_extraversion_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to use words like party, girls, baby, gettin, chillin while individuals that are not extraverted tend to use words like anime, manga, internet, japanese, drawing. Given these messages from a user, is this user extraverted according to the Big 5 personality traits? Select between yes or no\n\n",

    "itemdesc_extraversion_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to make friends easily while individuals that are not extraverted tend to avoid contact with others. Given these messages from a user, rate their extraversion according to the Big 5 personality traits. The options are low, medium, high.\nExtraversion:\n\n",

    "itemdesc_extraversion_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to make friends easily while individuals that are not extraverted tend to avoid contact with others. Given these messages from a user, is this user extraverted according to the Big 5 personality traits? Select between yes or no\n\n",

    "all_items_itemdesc_extraversion_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to make friends easily and do not mind being the centre of attention while individuals that are not extraverted tend to avoid contact with others and keep in the background. Given these messages from a user, is this user extraverted according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_positive_item_itemdesc_extraversion_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to not mind being the centre of attention while individuals that are not extraverted tend to avoid contact with others. Given these messages from a user, is this user extraverted according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_negative_item_itemdesc_extraversion_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to make friends easily while individuals that are not extraverted tend to keep in the background. Given these messages from a user, is this user extraverted according to the Big 5 personality traits? Select between yes or no\n\n",

    "both_alternate_items_itemdesc_extraversion_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to not mind being the centre of attention while individuals that are not extraverted tend to keep in the background. Given these messages from a user, is this user extraverted according to the Big 5 personality traits? Select between yes or no\n\n",
        
    "all_knowledge_extraversion_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are extraverted tend to be sociable, talkative, assertive and active while individuals that are not extraverted tend to be retiring, reserved and cautious. Also note that individuals who are extraverted tend to use words like party, girls, baby, gettin, chillin while individuals that are not extraverted tend to use words like anime, manga, internet, japanese, drawing. Furthermore, note that individuals who are extraverted tend to make friends easily and do not mind being the centre of attention while individuals that are not extraverted tend to avoid contact with others and keep in the background. Given these messages from a user, is this user extraverted according to the Big 5 personality traits? Select between yes or no\n\n",

    "openness_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, rate their openness to experiences. The options on the scale are low, medium, high.\nOpenness to experiences:\n\n",

    "openness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, is this user open to new experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "openness_nonew_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, is this user open to experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "textbook_openness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to new experiences tend to be intellectual, imaginative, sensitive and open-minded while individuals that are not open to new experiences tend to be down-to-earth, insensitive and conventional. Given these messages from a user, is this user open to new experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "textbook_openness_nonew_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to experiences tend to be intellectual, imaginative, sensitive and open-minded while individuals that are not open to experiences tend to be down-to-earth, insensitive and conventional. Given these messages from a user, is this user open to experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "wordlist_openness_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to new experiences tend to use words like universe, art, writing, soul, music while individuals that are not open to new experiences tend to use words like cant, dont, gud, nite, 2day. Given these messages from a user, rate their openness to experiences. The options on the scale are low, medium, high.\nOpenness to experiences:\n\n",

    "wordlist_openness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to new experiences tend to use words like universe, art, writing, soul, music while individuals that are not open to new experiences tend to use words like cant, dont, gud, nite, 2day. Given these messages from a user, is this user open to new experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "wordlist_openness_nonew_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to experiences tend to use words like universe, art, writing, soul, music while individuals that are not open to experiences tend to use words like cant, dont, gud, nite, 2day. Given these messages from a user, is this user open to experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "itemdesc_openness_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to new experiences tend to have a vivid imagination while individuals that are not open to new experiences tend to avoid philosophical discussions. Given these messages from a user, rate their openness to experiences according to the Big 5 personality traits. The options are low, medium, high.\nOpenness to experiences:\n\n",

    "itemdesc_openness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to new experiences tend to have a vivid imagination while individuals that are not open to new experiences tend to avoid philosophical discussions. Given these messages from a user, is this user open to new experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "itemdesc_openness_nonew_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to experiences tend to have a vivid imagination while individuals that are not open to experiences tend to avoid philosophical discussions. Given these messages from a user, is this user open to experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "all_items_itemdesc_openness_nonew_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to experiences tend to have a vivid imagination and enjoy wild flights of fantasy while individuals that are not open to experiences tend to avoid philosophical discussions and do not like poetry. Given these messages from a user, is this user open to experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_positive_item_itemdesc_openness_nonew_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to experiences tend to enjoy wild flights of fantasy while individuals that are not open to experiences tend to avoid philosophical discussions. Given these messages from a user, is this user open to experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_negative_item_itemdesc_openness_nonew_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to experiences tend to have a vivid imagination while individuals that are not open to experiences tend to not like poetry. Given these messages from a user, is this user open to experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "both_alternate_items_itemdesc_openness_nonew_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to experiences tend to enjoy wild flights of fantasy while individuals that are not open to experiences tend to not like poetry. Given these messages from a user, is this user open to experiences according to the Big 5 personality traits? Select between yes or no\n\n",

    "all_knowledge_openness_nonew_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are open to experiences tend to be intellectual, imaginative, sensitive and open-minded while individuals that are not open to experiences tend to be down-to-earth, insensitive and conventional. Also note that individuals who are open to experiences tend to use words like universe, art, writing, soul, music while individuals that are not open to experiences tend to use words like cant, dont, gud, nite, 2day. Furthermore, note that individuals who are open to experiences tend to have a vivid imagination and enjoy wild flights of fantasy while individuals that are not open to experiences tend to avoid philosophical discussions and do not like poetry. Given these messages from a user, is this user open to experiences according to the Big 5 personality traits? Select between yes or no\n\n",
    
    "conscientiousness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, is this user conscientious according to the Big 5 personality traits? Select between yes or no\n\n",

    "textbook_conscientiousness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are conscientious tend to be careful, thorough, organized and scrupulous while individuals that are not conscientious tend to be irresponsible, disorganized and unscrupulous. Given these messages from a user, is this user conscientious according to the Big 5 personality traits? Select between yes or no\n\n",

    "wordlist_conscientiousness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are conscientious tend to use words like blessed, ready, thankful, relaxing, vacation while individuals that are not conscientious tend to use words like fucking, pokemon, shit, gay, youtube. Given these messages from a user, is this user conscientious according to the Big 5 personality traits? Select between yes or no\n\n",

    "itemdesc_conscientiousness_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are conscientious tend to complete tasks successfully while individuals that are not conscientious tend to need a push to get started. Given these messages from a user, rate their conscientiousness according to the Big 5 personality traits. The options are low, medium, high.\nConscientiousness:\n\n",

    "itemdesc_conscientiousness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are conscientious tend to complete tasks successfully while individuals that are not conscientious tend to need a push to get started. Given these messages from a user, is this user conscientious according to the Big 5 personality traits? Select between yes or no\n\n",

    "all_items_itemdesc_conscientiousness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are conscientious tend to complete tasks successfully and are always prepared while individuals that are not conscientious tend to shirk their duties and need a push to get started. Given these messages from a user, is this user conscientious according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_positive_item_itemdesc_conscientiousness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are conscientious tend to be always prepared while individuals that are not conscientious tend to need a push to get started. Given these messages from a user, is this user conscientious according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_negative_item_itemdesc_conscientiousness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are conscientious tend to complete tasks successfully while individuals that are not conscientious tend to shirk their duties. Given these messages from a user, is this user conscientious according to the Big 5 personality traits? Select between yes or no\n\n",

    "both_alternate_items_itemdesc_conscientiousness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are conscientious tend to be always prepared while individuals that are not conscientious tend to shirk their duties. Given these messages from a user, is this user conscientious according to the Big 5 personality traits? Select between yes or no\n\n",

    "all_knowledge_conscientiousness_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are conscientious tend to be careful, thorough, organized and scrupulous while individuals that are not conscientious tend to be irresponsible, disorganized and unscrupulous. Also note that individuals who are conscientious tend to use words like blessed, ready, thankful, relaxing, vacation while individuals that are not conscientious tend to use words like fucking, pokemon, shit, gay, youtube. Furthermore, note that individuals who are conscientious tend to complete tasks successfully and are always prepared while individuals that are not conscientious tend to shirk their duties and need a push to get started. Given these messages from a user, is this user conscientious according to the Big 5 personality traits? Select between yes or no\n\n",

    "neuroticism_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Given these messages from a user, is this user neurotic according to the Big 5 personality traits? Select between yes or no\n\n",

    "textbook_neuroticism_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are neurotic tend to be anxious, depressed, angry and insecure while individuals that are not neurotic tend to be calm, poised and emotionally stable. Given these messages from a user, is this user neurotic according to the Big 5 personality traits? Select between yes or no\n\n",

    "wordlist_neuroticism_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are neurotic tend to use words like fucking, depression, pissed, anymore, lonely while individuals that are not neurotic tend to use words like success, lakers, basketball, workout, beach. Given these messages from a user, is this user neurotic according to the Big 5 personality traits? Select between yes or no\n\n",

    "itemdesc_neuroticism_classification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are neurotic tend to get stressed out easily while individuals that are not neurotic tend to feel comfortable with themselves. Given these messages from a user, rate their neuroticism according to the Big 5 personality traits. The options are low, medium, high.\nNeuroticism:\n\n",

    "itemdesc_neuroticism_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are neurotic tend to get stressed out easily while individuals that are not neurotic tend to feel comfortable with themselves. Given these messages from a user, is this user neurotic according to the Big 5 personality traits? Select between yes or no\n\n",

    "all_items_itemdesc_neuroticism_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are neurotic tend to get stressed out easily and often feel blue while individuals that are not neurotic tend to feel comfortable with themselves and are not easily bothered. Given these messages from a user, is this user neurotic according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_positive_item_itemdesc_neuroticism_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are neurotic tend to often feel blue while individuals that are not neurotic tend to feel comfortable with themselves. Given these messages from a user, is this user neurotic according to the Big 5 personality traits? Select between yes or no\n\n",

    "alternate_negative_item_itemdesc_neuroticism_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are neurotic tend to get stressed out easily while individuals that are not neurotic tend to not be easily bothered. Given these messages from a user, is this user neurotic according to the Big 5 personality traits? Select between yes or no\n\n",

    "both_alternate_items_itemdesc_neuroticism_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are neurotic tend to often feel blue while individuals that are not neurotic tend to not be easily bothered. Given these messages from a user, is this user neurotic according to the Big 5 personality traits? Select between yes or no\n\n",

    "all_knowledge_neuroticism_2wayclassification_most_recent_last": "Read the stream of Facebook posts from a user below. Each newline represents a new post. The posts are in order of date, the last one is the most recent.\n{}Note that individuals who are neurotic tend to be anxious, depressed, angry and insecure while individuals that are not neurotic tend to be calm, poised and emotionally stable. Also individuals who are neurotic tend to use words like fucking, depression, pissed, anymore, lonely while individuals that are not neurotic tend to use words like success, lakers, basketball, workout, beach. Furthermore, note that individuals who are neurotic tend to get stressed out easily and often feel blue while individuals that are not neurotic tend to feel comfortable with themselves and are not easily bothered. Given these messages from a user, is this user neurotic according to the Big 5 personality traits? Select between yes or no\n\n",
}